### PR TITLE
Temporary NFOs while the site is down

### PR DESCRIPTION
**Pull request by TheIceCreamTroll**
## Describe your changes
Creates some temporary NFOs as proposed in #59. Once the site is back redo these

I haven't watched any of these episodes, so I can't suggest a description or episode name to give them, but If someone has and wants to suggest something, I/they can update them.

## Checklist for submitting new .nfo files
- [x] I have removed the old .nfo files that are being replaced
- [x] I have validated that the new .nfo file works correctly in Plex
- [x] I have added a screenshot to my pull request, showing the episode in Plex with the correct metadata
- [x] I have updated the README, fixing the list of current missing episodes
- [x] I have modified exceptions.json, removing any exceptions no longer required

image
image
image
image
image
image

### CODE REVIEW

**Comment by jjnether** [comment]
> I haven't watched any of these episodes, so I can't suggest a description or episode name to give them, but If someone has and wants to suggest something, I/they can update them.

The episodes' metadata actually has the name they've assigned.

**Comment by TheIceCreamTroll** [comment]
Great find! Files have been updated

**Review by SpykerNZ — APPROVED** [review]
@TheIceCreamTroll looks good 👍 will have to do until the website is back up.

If users download these, they would have to update them manually once we update the descriptions. Could consider marking the nfo files in some way to indicate they have the descriptions missing, and make this process easier later on. Though is only possible if the nfos are still picked up by plex when names do not match 1:1,..

`One Pace/Season 14/One Pace - S14E125 - Magnificent Wings! My Name is Pell Guardian Deity of the Country! - DESC_MISSING.nfo`

It's a minor detail, and happy to have it merged as is

**Comment by TheIceCreamTroll** [comment]
It may be easier to keep the names the same so that people can just drag and drop the folder for the season / series and let their OS overwrite the existing files instead of going through one by one. As you said though, it's a minor detail. I'll merge it as is.

**Pull request merged**
