### PR TITLE
Add Wano 41 and Egghead 9

### PR DESCRIPTION
**Pull request by TheIceCreamTroll**
## Describe your changes
Adds Wano 41 and Egghead 9

image
image

## Checklist for submitting new .nfo files
- [x] I have removed the old .nfo files that are being replaced
- [x] I have validated that the new .nfo file works correctly in Plex
- [x] I have added a screenshot to my pull request, showing the episode in Plex with the correct metadata
- [x] I have updated the README, fixing the list of current missing episodes
- [x] I have modified exceptions.json, removing any exceptions no longer required

### CODE REVIEW

**Comment by SpykerNZ** [comment]
looks good, as usual :)

**Comment by jjnether** [comment]
@TheIceCreamTroll  I just got One Pace setup and was grateful to use this project for metadata. Can I ask where you've been getting descriptions while the One Pace website is down?

**Comment by TheOne320** [comment]
He has not been posting any updates since the website went down. I checked the source of his tool and it grabs the description from the One Pace site and so the only way to update the files now would be to manually create them.

**Comment by jjnether** [comment]
Makes sense, that's what I was wondering. Thanks!

**Comment by TheOne320** [comment]
Do you guys think they are scared of legal problems? The website is still down and without the website the tool cannot create anymore nfo files. Is there perhaps an alternative way of getting the descriptions so that we can update our libraries?

**Comment by TheIceCreamTroll** [comment]
Given that they're still releasing episodes and have stated that it's just an issue with their hosting provider, I doubt there are legal troubles brewing.

As for the episodes released since the site went down, we may want to go ahead and create the NFO files by hand, leave the descriptions blank, and update them when the site is back online.

We could also create and use our own descriptions until the official ones come out.

@SpykerNZ What do you think of this plan? I was hoping to wait out the outage initially, but a decent backlog has built up and there's not sign of the site being back up anytime soon.

**Comment by SpykerNZ** [comment]
@TheIceCreamTroll sounds like a good plan to me. can continue any discussions on the related PR: https://github.com/SpykerNZ/one-pace-for-plex/pull/64

**Pull request merged**
