### PR TITLE
Add If You Could Go Anywhere... The Adventures of the Straw Hats

### PR DESCRIPTION
**Pull request by TheIceCreamTroll**
## Describe your changes
Added "Add If You Could Go Anywhere... The Adventures of the Straw Hats" and shifted all seasons after it

A poster doesn't exist for this season yet. Plex should just default to using the series poster in the meantime

## Checklist for submitting new .nfo files
- [x] I have removed the old .nfo files that are being replaced
- [x] I have validated that the new .nfo file works correctly in Plex
- [x] I have updated the README, fixing the list of current missing episodes
- [x] I have modified exceptions.json, removing any exceptions no longer required

image

### CODE REVIEW

**Comment by SpykerNZ** [comment]
thanks for doing this! I hope we don't have to bump a bunch of episodes very often.

Also a bit of a shame the 'season' title doesn't really fit in with the rest...will leave for now as is technically correct and matches the One Pace website.

**Review by SpykerNZ — CHANGES_REQUESTED** [review]
I think this episode may need an exception added for the renaming to work correctly - see "The Trials of Koby-Meppo" as an example. 

```
"Season 11": {
		"The Trials of Koby-Meppo": 1
	},
```

**Comment by TheIceCreamTroll** [comment]
Nice catch! I'll look into this tomorrow

I might also try and throw together a script for shifting seasons. I've already made one (very janky) script for scraping NFO data from the One Pace site. Would be a nice addition

**Comment by TheIceCreamTroll** [comment]
> I think this episode may need an exception added for the renaming to work correctly - see "The Trials of Koby-Meppo" as an example.
> 
> ```
> "Season 11": {
> 		"The Trials of Koby-Meppo": 1
> 	},
> ```

Updated and tested `exceptions.json`. Renaming now works

**Review by SpykerNZ — APPROVED** [review]
Looks good now! :)

**Pull request merged**
