### PR TITLE
Rename Specials

### LINKED ISSUE #50: File renaming Option A - Windows Executable does nothing to the "Specials"
Like the title says. The windows executable rename.exe renamed everything except for the files in the "Specials" folder. They were completely ignored. I renamed them by hand.

### PR DESCRIPTION
**Pull request by TheIceCreamTroll**
## Describe your changes
Modify the rename script to support specials
closes #50 

image

### CODE REVIEW

**Review by SpykerNZ — COMMENTED** [review]
@TheIceCreamTroll Looks good. I presume the 'Specials' folder is picked up by Plex? Could you post a screenshot showing this season working correctly?

Changes to the script will also require the .exe to be re-compiled. I can add this to the PR once everyone is confirmed working. (unless you want to do this yourself)

**Comment by TheIceCreamTroll** [comment]
There shouldn't be any change in behavior from Plex since we already use the folder name `Specials` in this repo, and I imagine people just copy/paste that into their servers.

Will post a screenshot in a min, need to sort out an unrelated Plex issue rq

**Comment by TheIceCreamTroll** [comment]
Wait, there's a mismatch due to the filename fitting the normal regex `DRYRUN: "[One Pace][823-824] Whole Cake Island 01 [720p][EDB72EE5].mp4" -> "One Pace - S33E01 - A World Abuzz.mp4"`

Gonna take another crack at it

**Comment by TheIceCreamTroll** [comment]
now it's actually working
image

image

I'll leave creating the exe to you. I'm not familiar with that process

**Comment by SpykerNZ** [comment]
@TheIceCreamTroll Not sure how to access the branch on your repo, so will merge and then push the .exe directly.

**Pull request merged**
